### ISSUE TITLE
Build failure on macOS 10.14.6

### ISSUE THREAD

**Issue by McDutchie** [emersion/mrsh#119]
mrsh currently fails to build on macOS 10.14.6 (Apple clang version 11.0.0 (clang-1100.0.33.12)).

```
$ ninja -C ../build
ninja: Entering directory `../build'
[52/60] Compiling C object 'mrsh@exe/frontend_readline.c.o'.
FAILED: mrsh@exe/frontend_readline.c.o 
ccache cc -Imrsh@exe -I. -I../mrsh -I../mrsh/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c99 -g -Wundef -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wstrict-prototypes -Wredundant-decls -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wformat=2 -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unused-result -DHAVE_READLINE -Os -MD -MQ 'mrsh@exe/frontend_readline.c.o' -MF 'mrsh@exe/frontend_readline.c.o.d' -o 'mrsh@exe/frontend_readline.c.o' -c ../mrsh/frontend/readline.c
../mrsh/frontend/readline.c:28:2: error: implicit declaration of function 'rl_replace_line' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rl_replace_line("", 0);
        ^
../mrsh/frontend/readline.c:28:2: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
2 errors generated.
[56/60] Compiling C object 'example/50d858e@@highlight@exe/highlight.c.o'.
ninja: build stopped: subcommand failed.
```

**Comment by emersion** [comment]
Is it happening using editline or readline?

**Comment by McDutchie** [comment]
Looks like readline. Here is the output of `meson ../build`:

```
The Meson build system
Version: 0.52.0
Source dir: /usr/local/src/mrsh/mrsh
Build dir: /usr/local/src/mrsh/build
Build type: native build
Project name: mrsh
Project version: 0.0.0
C compiler for the host machine: ccache cc (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.12)")
C linker for the host machine: APPLE ld 520
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wlogical-op: NO 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wfloat-equal: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=2: NO 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Woverflow: YES 
Compiler for C supports arguments -Wformat=2: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wno-unused-result: YES 
Library readline found: YES
Checking if "-Wl,--version-script" links: NO 
Compiler for C supports link arguments -Wl,-exported_symbols_list /usr/local/src/mrsh/mrsh/libmrsh.darwin.sym: YES 
Program ./harness.sh found: YES (/usr/local/src/mrsh/mrsh/test/./harness.sh)
Program sh found: YES (/bin/sh)
Message: 
Features:
  readline: true
  examples: true
Build targets in project: 3
Found ninja-1.9.0 at /opt/local/bin/ninja
```

**Comment by emersion** [comment]
Hmm, it seems like the library is called `readline` even though it's BSD libedit, so `HAVE_READLINE` is incorrectly set to true. We should probably check whether functions are defined instead (just like https://github.com/hercules-team/augeas/issues/256).
